// ----------------------------------------------------------------------------
// postgres.bicep
// Azure Database for PostgreSQL Flexible Server.
//   * Zone-redundant HA (prod) / SameZone (non-prod).
//   * VNet-injected (delegated subnet) — no public endpoint.
//   * TLS 1.2 enforced; SSL required.
//   * Automated backups: 35 days, geo-redundant in prod.
//   * Admin password generated by caller (main.bicep) and stored in Key
//     Vault; this module accepts only the resulting secret reference.
//   * Per-firm databases via `firmDatabases` parameter; sharding to a second
//     server is a matter of instantiating this module twice with different
//     `serverNameSuffix` values.
// ----------------------------------------------------------------------------
param location string
param postgresName string
param tags object
param subnetId string
param privateDnsZoneId string
param workspaceId string

@allowed([ 'ZoneRedundant', 'SameZone', 'Disabled' ])
param highAvailabilityMode string = 'ZoneRedundant'

@allowed([
  'Standard_B2s'
  'Standard_D2ds_v5'
  'Standard_D4ds_v5'
  'Standard_D8ds_v5'
])
param skuName string = 'Standard_D2ds_v5'

@allowed([ 'Burstable', 'GeneralPurpose', 'MemoryOptimized' ])
param skuTier string = 'GeneralPurpose'

param storageSizeGB int = 128
@allowed([ 'Disabled', 'Enabled' ])
param geoRedundantBackup string = 'Enabled'

@secure()
param administratorLoginPassword string
param administratorLogin string = 'ctaa_owner'

@description('Per-firm database names. Defaults to a single "ctaa" DB.')
param firmDatabases array = [ 'ctaa' ]

resource pg 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: postgresName
  location: location
  tags: tags
  sku: { name: skuName, tier: skuTier }
  properties: {
    version: '16'
    administratorLogin: administratorLogin
    administratorLoginPassword: administratorLoginPassword
    storage: { storageSizeGB: storageSizeGB, autoGrow: 'Enabled' }
    backup: {
      backupRetentionDays: 35
      geoRedundantBackup: geoRedundantBackup
    }
    highAvailability: { mode: highAvailabilityMode }
    network: {
      delegatedSubnetResourceId: subnetId
      privateDnsZoneArmResourceId: privateDnsZoneId
      publicNetworkAccess: 'Disabled'
    }
    authConfig: {
      activeDirectoryAuth: 'Enabled'
      passwordAuth: 'Enabled'  // emergency break-glass; rotate often
      tenantId: subscription().tenantId
    }
  }
}

resource pgRequireSSL 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = {
  name: 'require_secure_transport'
  parent: pg
  properties: { value: 'ON', source: 'user-override' }
}

resource pgLogStatement 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = {
  name: 'log_statement'
  parent: pg
  properties: { value: 'ddl', source: 'user-override' }
}

resource pgLogConnections 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = {
  name: 'log_connections'
  parent: pg
  properties: { value: 'on', source: 'user-override' }
}

resource pgRowSecurity 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = {
  name: 'row_security'
  parent: pg
  properties: { value: 'on', source: 'user-override' }
}

resource dbs 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' = [for d in firmDatabases: {
  name: d
  parent: pg
  properties: { charset: 'UTF8', collation: 'en_US.utf8' }
}]

resource diag 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'pg-to-log'
  scope: pg
  properties: {
    workspaceId: workspaceId
    logs: [
      { categoryGroup: 'allLogs', enabled: true }
    ]
    metrics: [ { category: 'AllMetrics', enabled: true } ]
  }
}

output serverFqdn string = pg.properties.fullyQualifiedDomainName
output serverId string = pg.id
output databases array = firmDatabases
